# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Linux x64
      run: dotnet publish --sc -c Release -a x64 --os linux
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoRecordingJoiner_linux_x64
        path: bin/Release/net9.0/linux-x64/publish/VideoRecordingJoiner
